city/urls.py
from django.urls import path


from city.apps import CityConfig
from city.views import CityCreateView, CityListView, CityDetailView, CityUpdateView, CityDeleteView

app_name = CityConfig.name
urlpatterns = [
    path('create/', CityCreateView.as_view(), name='create'),
    path('', CityListView.as_view(), name='list'),
    path('view/<int:pk>/', CityDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', CityUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls')),
                  path('city/', include('city.urls', namespace='city')),
                  path('users/', include('users.urls', namespace='users')),
              ]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

city/models.py
from django.db import models

NULLABLE = {
    'null': True,
    'blank': True
}

NOT_NULLABLE = {
    'null': False,
    'blank': False
}


class City(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='Содержимое')
    img = models.ImageField(upload_to='city_img/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, **NOT_NULLABLE, verbose_name='Дата создания')
    publication = models.BooleanField(**NULLABLE, default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')



    def __str__(self):
        return f'{self.title} : {self.body}'

    def __repr__(self):
        return 'Image(%s, %s)' % (self.body, self.img)

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

city/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from city.models import City


class CityCreateView(CreateView):
    model = City
    fields = ('title', 'body', 'img')
    success_url = reverse_lazy('city:list')

    def form_valid(self, form):
        if form.is_valid():
            new_city = form.save()
            new_city.slug = slugify(new_city.title)
            new_city.save()

        return super().form_valid(form)


class CityUpdateView(UpdateView):
    model = City
    fields = ('title', 'body', 'img')
    success_url = reverse_lazy('city:list')

class CityListView(ListView):
    model = City
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class CityDetailView(DetailView):
    model = City

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class CityDeleteView(DeleteView):
    model = City
    success_url = reverse_lazy('city:list')

city/templates/city/city_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить город "{{ object.title }}"?</p>
                    <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                    <a class="btn btn-outline-warning" href="{% url 'city:list' %}">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

city/templates/city/city_detail.html
{% extends 'main/base.html' %}

{% block content %}
    {% load image_tag %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="col-12">
                <div class="row">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    {{ object.title }} ({{ object.slug }})
                                </h3>
                            </div>
                            <div class="card-body">
                                <table class="table">
                                    <tr>
                                        <td>{{ object.body }}</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="card-footer">
                                Прочитано {{ object.views_count }} раз.
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <img src="{% media_path object.img %}" class="card-img-top" alt="city"/>
                    </div>
                </div>
                <a class="btn btn-outline-primary" href="{% url 'city:list' %}">назад</a>
            </div>
        </div>
    </div>

{% endblock %}

city/templates/city/city_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a class="btn btn-outline-danger" href="{% url 'city:list' %}">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

city/templates/city/city_list.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
{% load image_tag %}
<div class="col-12 mb-4">
    <a class="btn btn-outline-primary" href="{% url 'city:create' %}">Добавить город</a>
</div>
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img src="{% media_path object.img %}" class="card-img-top" alt=""/>
                <div class="card-body">
                    <p class="card-text">{{ object.title }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <p>
                                <a href="{% url 'city:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                                <a href="{% url 'city:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                                <a href="{% url 'city:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-danger">Delete</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}