city/urls.py
from django.urls import path


from city.apps import CityConfig
from city.views import CityCreateView, CityListView, CityDetailView, CityUpdateView, CityDeleteView

app_name = CityConfig.name
urlpatterns = [
    path('create/', CityCreateView.as_view(), name='create'),
    path('', CityListView.as_view(), name='list'),
    path('view/<int:pk>/', CityDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', CityUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls')),
                  path('city/', include('city.urls', namespace='city')),
                  path('users/', include('users.urls', namespace='users')),
              ]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, LoginView, LogoutView, generate_password

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_password, name='generate_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {
    'null': True,
    'blank': True
}

NOT_NULLABLE = {
    'null': False,
    'blank': False
}


class User(AbstractUser):
    username = None
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='Страна', **NULLABLE)
    email = models.EmailField(unique=True, verbose_name='Почта')
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.urls import reverse_lazy
from django import forms

from catalog.forms import StyleForm
from users.models import User


class UserRegisterForm(StyleForm, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
        success_url = reverse_lazy('users:login')


class UserProfileForm(StyleForm, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'country', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets
import string
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from django.conf import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.shortcuts import render, redirect

class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'


    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='Добро пожаловать!',
            message='Регистрация прошла успешно!',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)



class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

def generate_password(request):
    alphabet = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(secrets.choice(alphabet) for i in range(8))  # генерируем пароль длиной 8 символов
    request.user.set_password(password)
    request.user.save()

    send_mail(
        subject='Вы сменили пароль!',
        message=f'Ваш новый пароль: {password}!',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )

    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-15">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Вход</h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Войти</button>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-15">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Регистрация</h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Регистрация</button>
                            <a class="btn btn-outline-warning" href="{% url 'catalog:category' %}">Отмена</a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-15">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Профиль</h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Сохранить</button>
                            <a class="btn btn-outline-warning" href="{% url 'catalog:category' %}">Отмена</a>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'users:generate_password' %}" class="btn btn-success">Сгенерировать пароль</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}