catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog import views
from catalog.apps import CatalogConfig
from catalog.views import CategoryListView, ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ProductDetailView

app_name = CatalogConfig.name
urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('product/<int:pk>/', cache_page(60)(ProductListView.as_view()), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/detail', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('contacts/', views.contacts, name='contacts')
    ]

city/urls.py
from django.urls import path


from city.apps import CityConfig
from city.views import CityCreateView, CityListView, CityDetailView, CityUpdateView, CityDeleteView

app_name = CityConfig.name
urlpatterns = [
    path('create/', CityCreateView.as_view(), name='create'),
    path('', CityListView.as_view(), name='list'),
    path('view/<int:pk>/', CityDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', CityUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls')),
                  path('city/', include('city.urls', namespace='city')),
                  path('users/', include('users.urls', namespace='users')),
              ]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, LoginView, LogoutView, generate_password

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_password, name='generate_password'),
]

catalog/models/category.py
from django.db import models

NULLABLE = {
    'null': True,
    'blank': True
}

NOT_NULLABLE = {
    'null': False,
    'blank': False
}


class Category(models.Model):
    name = models.CharField(max_length=50, **NOT_NULLABLE)
    desc = models.TextField(max_length=100, **NULLABLE)

    def __str__(self):
        return f'{self.name} : {self.desc}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

catalog/models/products.py
from django.db import models
from django.shortcuts import render

NULLABLE = {
    'null': True,
    'blank': True
}

NOT_NULLABLE = {
    'null': False,
    'blank': False
}


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование', **NOT_NULLABLE)
    desc = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='product', null=True, blank=True, verbose_name='Изображение')
    category_id = models.ForeignKey('Category', on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0, **NOT_NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, **NOT_NULLABLE)
    update_at = models.DateTimeField(auto_now=True, **NOT_NULLABLE)

    def __str__(self):
        return f'{self.name} : {self.desc}'

    def __repr__(self):
        return 'Image(%s, %s)' % (self.desc, self.image)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('price',)

catalog/models/version.py
from django.db import models

from catalog.models.products import Product

NULLABLE = {
    'null': True,
    'blank': True
}

NOT_NULLABLE = {
    'null': False,
    'blank': False
}


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    num_version = models.IntegerField(verbose_name='номер версии', **NULLABLE)
    name_version = models.CharField(max_length=100, null=True, blank=True, verbose_name='Название версии')
    current_version = models.BooleanField(**NULLABLE, default=True, verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.name_version}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.models.products import Product
from catalog.models.version import Version


class StyleForm:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'sign_current_version':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleForm, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category_id'].empty_label = 'Категория не выбрана'

    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        tags = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        name = self.cleaned_data['name']

        for tag in tags:
            if name in tag:
                raise ValidationError('Недопустимое значение')
        return name

    def clean_desc(self):
        tags = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        desc = self.cleaned_data['desc']

        for tag in tags:
            if desc in tag:
                raise ValidationError('Недопустимое значение')
        return desc


class VersionForm(StyleForm, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.db.models import Q
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Category, Product
from catalog.models.version import Version


class CategoryListView(ListView):
    model = Category
    template_name = 'main/index.html'


# def index(request):
#     context = {
#         'object_list': Category.objects.all(),
#         'title': 'Иномарка З/Ч'
#     }
#     return render(request, 'main/index.html', context)


# def product(request, pk):
#     product_list = Category.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(category_id=pk),
#         'title': product_list.name
#     }
#     return render(request, 'main/product.html', context)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'main/product_detail.html'



class ProductListView(ListView):
    model = Product
    template_name = 'main/product.html'
    success_url = reverse_lazy('catalog:category')
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        product_l = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['title'] = product_l.name

        return context_data


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}) {message}')
    return render(request, 'main/contacts.html')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'main/product_form.html'
    success_url = reverse_lazy('catalog:category')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'main/product_form.html'
    success_url = reverse_lazy('catalog:category')

    def get_context_data(self, **kwargs):
        contex_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        contex_data['formset'] = formset
        return contex_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'main/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:category')

catalog/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Internet Shop</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>
<body>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-471ETHFK21"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-471ETHFK21');

</script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
     (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(39705265, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true });
</script>
<noscript>
    <div><img src="https://mc.yandex.ru/watch/39705265" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript> <!-- /Yandex.Metrika counter -->
<!-- Yandex.RTB -->
<script>window.yaContextCb=window.yaContextCb||[]</script>
<script src="https://yandex.ru/ads/system/context.js" async></script>

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8588635311388465" crossorigin="anonymous"></script>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Меню</h4>
              <ul class="list-unstyled">
                  <li><a href="/" class="text-white">Главная</a></li>
                  <li><a href="{% url 'city:list' %}" class="text-white">Города</a></li>
                  {% if user.is_authenticated %}
                    <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                    <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                  {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>


<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Internet Shop</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/main/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/main/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
    {% load static %}
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img src="{% static 'images/1parts.jpeg' %}" alt="З/Ч" style="width: 350px; height: 225px;">
                <div class="card-body">
                    <p class="card-text">{{ object.name }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <p>
                                <a href="{% url 'catalog:product' object.pk %}" class="btn btn-sm btn-outline-secondary">открыть</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/main/product.html
{% extends 'main/base.html' %}
{% load image_tag %}
{% block content %}

<p>
    <a href="{% url 'catalog:category' %}" class="btn btn-outline-secondary">назад</a>
</p>
<p>
    <a href="{% url 'catalog:product_create' %}" class="btn btn-outline-primary">Добавить продукт</a>
</p>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4 mb-3">
        <div class="card mb-4 box-shadow">
            <img src="{% media_path object.image %}" class="card-img-top" alt=""/>
                <div class="card-body">
                    <p class="card-text">{{ object.name }} </p>
                    <p class="card-text">{{object.desc|truncatewords:25}} </p>
                    <p class="card-text">{{object.price|truncatewords:25}} руб. </p>
                    <span class="text-muted">{{object.created_at}}</span>
                    {% for version in object.version_set.all %}
                    <p>Версия {{ version.num_version }}: {{ version.name_version }}</p>
                    {% endfor %}
                    <div class="d-flex justify-content-between align-items-center">
                    </div>
                    {% if user.is_authenticated %}
                    <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-outline-secondary active" aria-current="page">View</a>
                    <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-outline-success">Edit</a>
                    <a href="{% url 'catalog:product_delete' object.pk %}" type="button" class="btn btn-outline-danger">Delete</a>
                    {% endif %}
                </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Хотите удалить продукт "{{ object.name }}"?</p>
                    <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                    <a class="btn btn-outline-warning" href="{% url 'catalog:product' object.pk %}">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/main/product_detail.html
{% extends 'main/base.html' %}

{% block content %}
{% load static %}
{% load image_tag %}
<div class="row">
    <div class="col-md-4">
        <h2>{{product.name}}</h2>
        <img src="{% media_path object.image %}" alt="{{product.name}}" class="card-img-top" />
        <p>Категория {{product.category_id}}</p>
        <p>Описание: {{product.desc}}</p>
        <p>Цена: {{product.price}} руб.</p>
        <p>Клиент: {{ object.client|default:'не забронировано'}}</p>
        <a href="{% url 'catalog:category' %}" class="btn btn-success">назад</a>
    </div>
</div>
{% endblock %}

catalog/templates/main/product_form.html
{% extends 'main/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Добавление товара
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {% for f in form %}
                    <p><label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }}: </label>{{ f }}</p>
                    <div class="form-error">{{f.errors}}</div>
                    {% endfor %}
                    {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-outline-success">Добавить</button>
                    <a class="btn btn-outline-warning" href="{% url 'catalog:category' %}">Отмена</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Информация
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}